let keylist = [
    ['Backspace', 'Backspace', '8'],
    ['Tab', 'Tab', '9'],
    ['Enter', 'Enter<br/>NumpadEnter', '13'],
    ['Shift', 'ShiftLeft<br/>ShiftRight', '16'],
    ['Control', 'ControlLeft<br/>ControlRight', '17'],
    ['Alt', 'AltLeft<br/>AltRight', '18'],
	['Pause', 'Pause', '19'],
    ['CapsLock', 'CapsLock', '20'],

    [' ', 'Space', '32'],
    ['PageUp', 'PageUp<br/>Numpad9', '33'],
    ['PageDown', 'PageDown<br/>Numpad3', '34'],
    ['End', 'End<br/>Numpad1', '35'],
    ['Home', 'Home<br/>Numpad7', '36'],
    ['ArrowLeft', 'ArrowLeft<br/>Numpad4', '37'],
    ['ArrowUp', 'ArrowUp<br/>Numpad8', '38'],
    ['ArrowRight', 'ArrowRight<br/>Numpad6', '39'],
    ['ArrowDown', 'ArrowDown<br/>Numpad2', '40'],

    ['PrintScreen', 'PrintScreen', '44'],
    ['Insert', 'Insert<br/>Numpad0', '45'],
    ['Delete', 'Delete<br/>NumpadDecimal', '46'],

    ['0<br/>)', 'Digit0', '48'],
    ['1<br/>!', 'Digit1', '49'],
    ['2<br/>@<br/>"', 'Digit2', '50'],
    ['3<br/>#<br/>№', 'Digit3', '51'],
    ['4<br/>$<br/>;', 'Digit4', '52'],
    ['5<br/>%', 'Digit5', '53'],
    ['6<br/>^<br/>:', 'Digit6', '54'],
    ['7<br/>&<br/>?', 'Digit7', '55'],
    ['8<br/>*', 'Digit8', '56'],
    ['9<br/>(', 'Digit9', '57'],

    ['a<br/>A', 'KeyA', '65'],
    ['b<br/>B', 'KeyB', '66'],
    ['c<br/>C', 'KeyC', '67'],
    ['d<br/>D', 'KeyD', '68'],
    ['e<br/>E', 'KeyE', '69'],
    ['f<br/>F', 'KeyF', '70'],
    ['g<br/>G', 'KeyG', '71'],
    ['h<br/>H', 'KeyH', '72'],
    ['i<br/>I', 'KeyI', '73'],
    ['j<br/>J', 'KeyJ', '74'],
    ['k<br/>K', 'KeyK', '75'],
    ['l<br/>L', 'KeyL', '76'],
    ['m<br/>M', 'KeyM', '77'],
    ['n<br/>N', 'KeyN', '78'],
    ['o<br/>O', 'KeyO', '79'],
    ['p<br/>P', 'KeyP', '80'],
    ['q<br/>Q', 'KeyQ', '81'],
    ['r<br/>R', 'KeyR', '82'],
    ['s<br/>S', 'KeyS', '83'],
    ['t<br/>T', 'KeyT', '84'],
    ['u<br/>U', 'KeyU', '85'],
    ['v<br/>V', 'KeyV', '86'],
    ['w<br/>W', 'KeyW', '87'],
    ['x<br/>X', 'KeyX', '88'],
    ['y<br/>Y', 'KeyY', '89'],
    ['z<br/>Z', 'KeyZ', '90'],
    ['Meta', 'MetaLeft', '91'],

    ['0', 'Numpad0', '96'],
    ['1', 'Numpad1', '97'],
    ['2', 'Numpad2', '98'],
    ['3', 'Numpad3', '99'],
    ['4', 'Numpad4', '100'],
    ['5', 'Numpad5', '101'],
    ['6', 'Numpad6', '102'],
    ['7', 'Numpad7', '103'],
    ['8', 'Numpad8', '104'],
    ['9', 'Numpad9', '105'],
    ['*', 'NumpadMultiply', '106'],
    ['+', 'NumpadAdd', '107'],


    ['-', 'NumpadSubstract', '109'],

    ['/', 'NumpadDivide', '111'],
    ['F1', 'F1', '112'],
    ['F2', 'F2', '113'],
    ['F3', 'F3', '114'],
    ['F4', 'F4', '115'],
    ['F5', 'F5', '116'],
    ['F6', 'F6', '117'],
    ['F7', 'F7', '118'],
    ['F8', 'F8', '119'],
    ['F9', 'F9', '120'],
    ['F10', 'F10', '121'],
    ['F11', 'F11', '122'],
    ['F12', 'F12', '123'],

    ['NumLock', 'NumLock', '144'],

    ['AudioVolumeMute', 'AudioVolumeMute', '173'],
    ['AudioVolumeDown', 'AudioVolumeDown', '174'],
    ['AudioVolumeUp', 'AudioVolumeUp', '175'],
    ['MediaTrackNext', 'MediaTrackNext', '176'],
    ['MediaTrackPrevious', 'MediaTrackPrevious', '177'],
    ['MediaPlayPause', 'MediaPlayPause', '179'],
    
    [';<br/>:', 'Semicolon', '186'],
    ['=<br/>+', 'Equal', '187'],
    [',<br/><', 'Comma', '188'],
    ['-<br/>_', 'Minus', '189'],
    ['.<br/>>', 'Period', '190'],
    ['/<br/>?', 'Slash', '191'],
    ['`<br/>~', 'Backquote', '192'],

    ['\\<br/>|', 'Backslash', '220'],
    ['\'<br/>"', 'Quote', '222'],

    ['Unidentified', '', '255'],
];

let keylistru = [
    ['а<br/>А', 'KeyF', '70'],
    ['б<br/>Б', 'Comma', '188'],
    ['в<br/>В', 'KeyD', '68'],
    ['г<br/>Г', 'KeyU', '85'],
    ['д<br/>Д', 'KeyL', '76'],
    ['е<br/>Е', 'KeyT', '84'],
    ['ё<br/>Ё', 'Backquote', '192'],
    ['ж<br/>Ж', 'Semicolon', '186'],
    ['з<br/>З', 'KeyP', '80'],
    ['и<br/>И', 'Key', '70'],
    ['й<br/>Й', 'Key', '70'],
    ['к<br/>К', 'Key', '70'],
    ['л<br/>Л', 'Key', '70'],
];

/*
['a<br/>A', 'KeyA', '65'],
    ['b<br/>Q', 'KeyB', '66'],
    ['c<br/>Q', 'KeyC', '67'],
    ['e<br/>Q', 'KeyE', '69'],
    ['g<br/>Q', 'KeyG', '71'],
    ['h<br/>Q', 'KeyH', '72'],
    ['i<br/>Q', 'KeyI', '73'],
    ['j<br/>Q', 'KeyJ', '74'],
    ['k<br/>Q', 'KeyK', '75'],
    ['m<br/>Q', 'KeyM', '77'],
    ['n<br/>Q', 'KeyN', '78'],
    ['o<br/>Q', 'KeyO', '79'],
    ['p<br/>Q', 'KeyP', '80'],
    ['q<br/>Q', 'KeyQ', '81'],
    ['r<br/>Q', 'KeyR', '82'],
    ['s<br/>Q', 'KeyS', '83'],
    ['t<br/>Q', 'KeyT', '84'],
    ['v<br/>Q', 'KeyV', '86'],
    ['w<br/>Q', 'KeyW', '87'],
    ['x<br/>Q', 'KeyX', '88'],
    ['y<br/>Y', 'KeyY', '89'],
    ['z<br/>Z', 'KeyZ', '90'],
    ['Meta', 'MetaLeft', '91'],
*/